### ISSUE TITLE
[BUG] Bagel-cli doesn't work after installation

### ISSUE THREAD

**Issue by maelleF** [neurobagel/bagel-cli#179]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Error message
```
(NeuroBagel) maellef@Coucou:~/git/bulk_annotations$ bagel --help
Traceback (most recent call last):
  File "/home/maellef/env/NeuroBagel/bin/bagel", line 5, in <module>
    from bagel.cli import bagel
  File "/home/maellef/git/bagel-cli/bagel/cli.py", line 9, in <module>
    import bagel.bids_utils as butil
  File "/home/maellef/git/bagel-cli/bagel/bids_utils.py", line 6, in <module>
    from bagel import mappings, models
  File "/home/maellef/git/bagel-cli/bagel/models.py", line 12, in <module>
    class Bagel(BaseModel, extra=Extra.forbid):
  File "/home/maellef/git/bagel-cli/bagel/models.py", line 16, in Bagel
    identifier: str = Field(
  File "/home/maellef/env/NeuroBagel/lib/python3.10/site-packages/pydantic/fields.py", line 755, in Field
    raise PydanticUserError('`regex` is removed. use `pattern` instead', code='removed-kwargs')
pydantic.errors.PydanticUserError: `regex` is removed. use `pattern` instead

For further information visit https://errors.pydantic.dev/2.0.3/u/removed-kwargs
```
### Environment

- OS: Ubuntu 22.04.2 lts
- Python/Node version: 3.10.6

### How to reproduce

try installing without container

**Comment by surchs** [comment]
Probably linked to https://github.com/neurobagel/bagel-cli/issues/180
